version: '3.4'

# -----------------------------------------------------------------------------
# "extensions", these are extended by the containers below
x-base: &base
    image: mongo:4
    networks:
        - mongozone

x-config: &config
    <<: *base
    expose: ["27019"]
    command:
        - "mongod"
        - "--configsvr"
        - "--sslMode"
        - "preferSSL"
        - "--auth"
        - "--sslPEMKeyFile"
        - "/data/ssl/secret.pem"
        - "--sslCAFile"
        - "/data/ssl/mongoCA.crt"
        - "--sslClusterFile"
        - "/data/ssl/secret.pem"
        - "--sslPEMKeyPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--sslClusterPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--clusterAuthMode"
        - "x509"
        - "--replSet"
        - "configReplicationSet"

x-shard: &shard
    <<: *base
    expose: ["27018"]

x-alpha: &alpha
    <<: *shard
    command:
        - "mongod"
        - "--shardsvr"
        - "--sslMode"
        - "preferSSL"
        - "--auth"
        - "--sslPEMKeyFile"
        - "/data/ssl/secret.pem"
        - "--sslCAFile"
        - "/data/ssl/mongoCA.crt"
        - "--sslClusterFile"
        - "/data/ssl/secret.pem"
        - "--sslPEMKeyPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--sslClusterPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--clusterAuthMode"
        - "x509"
        - "--replSet"
        - "alphaReplicationSet"

x-beta: &beta
    <<: *shard
    command:
        - "mongod"
        - "--shardsvr"
        - "--sslMode"
        - "preferSSL"
        - "--auth"
        - "--sslPEMKeyFile"
        - "/data/ssl/secret.pem"
        - "--sslCAFile"
        - "/data/ssl/mongoCA.crt"
        - "--sslClusterFile"
        - "/data/ssl/secret.pem"
        - "--sslPEMKeyPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--sslClusterPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--clusterAuthMode"
        - "x509"
        - "--replSet"
        - "betaReplicationSet"

x-gamma: &gamma
    <<: *shard
    command:
        - "mongod"
        - "--shardsvr"
        - "--sslMode"
        - "preferSSL"
        - "--auth"
        - "--sslPEMKeyFile"
        - "/data/ssl/secret.pem"
        - "--sslCAFile"
        - "/data/ssl/mongoCA.crt"
        - "--sslClusterFile"
        - "/data/ssl/secret.pem"
        - "--sslPEMKeyPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--sslClusterPassword"
        - "${SSL_PEM_PASSWORD}"
        - "--clusterAuthMode"
        - "x509"
        - "--replSet"
        - "gammaReplicationSet"

# -----------------------------------------------------------------------------

services:

    config-1:
        <<: *config
        container_name: mongo-cluster-config1-container
        volumes:
            - "./volumes/config-1:/data"

    config-2:
        <<: *config
        container_name: mongo-cluster-config2-container
        volumes:
            - "./volumes/config-2:/data"

    config-3:
        <<: *config
        container_name: mongo-cluster-config3-container
        volumes:
            - "./volumes/config-3:/data"

    alpha-1:
        <<: *alpha
        container_name: mongo-cluster-alpha1-container
        volumes:
            - "./volumes/alpha-1:/data"

    alpha-2:
        <<: *alpha
        container_name: mongo-cluster-alpha2-container
        volumes:
            - "./volumes/alpha-2:/data"

    alpha-3:
        <<: *alpha
        container_name: mongo-cluster-alpha3-container
        volumes:
            - "./volumes/alpha-3:/data"

    beta-1:
        <<: *beta
        container_name: mongo-cluster-beta1-container
        volumes:
            - "./volumes/beta-1:/data"

    beta-2:
        <<: *beta
        container_name: mongo-cluster-beta2-container
        volumes:
            - "./volumes/beta-2:/data"

    beta-3:
        <<: *beta
        container_name: mongo-cluster-beta3-container
        volumes:
            - "./volumes/beta-3:/data"

    gamma-1:
        <<: *gamma
        container_name: mongo-cluster-gamma1-container
        volumes:
            - "./volumes/gamma-1:/data"

    gamma-2:
        <<: *gamma
        container_name: mongo-cluster-gamma2-container
        volumes:
            - "./volumes/gamma-2:/data"

    gamma-3:
        <<: *gamma
        container_name: mongo-cluster-gamma3-container
        volumes:
            - "./volumes/gamma-3:/data"
#
#    mongos-1:
#        <<: *base
#        container_name: mongo-shard-router-1
#        command:
#            - "mongos"
#            - "--configdb"
#            - "configReplicationSet/config-1:27019,config-2:27019,config-3:27019"
#            - "--bind_ip=0.0.0.0"
#

networks:
    mongozone:
        external: false

